In [5]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\acer\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\acer\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd

In [12]:
labels = ['a','b','c']
my_list = [1,2,3]
arr= np.array([1,2,3])
dic = {1:10, 2:20, 3:30}

In [13]:
pd.Series(my_list)

0    1
1    2
2    3
dtype: int64

In [14]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [16]:
pd.Series(arr)

0    1
1    2
2    3
dtype: int64

In [17]:
pd.Series(dic)

1    10
2    20
3    30
dtype: int64

In [18]:
pd.Series(my_list, index=labels)

a    1
b    2
c    3
dtype: int64

In [19]:
pd.Series(my_list, index=arr)

1    1
2    2
3    3
dtype: int64

In [20]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [21]:
pd.Series(dic, index=labels)

a   NaN
b   NaN
c   NaN
dtype: float64

In [ ]:
# Data Frames

In [22]:
people = {
    "Name": ["Ram", "Shyam", "Hari", "Sita"],
    "Age": [20, 22, 21, 23],
    "City": ["Butwal", "Kathmandu", "Pokhara", "Chitwan"],
    "Salary": [25000, 30000, 28000, 35000]
}

print(people)

{'Name': ['Ram', 'Shyam', 'Hari', 'Sita'], 'Age': [20, 22, 21, 23], 'City': ['Butwal', 'Kathmandu', 'Pokhara', 'Chitwan'], 'Salary': [25000, 30000, 28000, 35000]}

In [23]:
pd.DataFrame(people)

    Name  Age       City  Salary
0    Ram   20     Butwal   25000
1  Shyam   22  Kathmandu   30000
2   Hari   21    Pokhara   28000
3   Sita   23    Chitwan   35000

In [26]:
d_list = [
    ["Ram", 20, "Butwal", 25000],
    ["Shyam", 22, "Kathmandu", 30000],
    ["Hari", 21, "Pokhara", 28000],
    ["Sita", 23, "Chitwan", 35000]
]

print(people)

{'Name': ['Ram', 'Shyam', 'Hari', 'Sita'], 'Age': [20, 22, 21, 23], 'City': ['Butwal', 'Kathmandu', 'Pokhara', 'Chitwan'], 'Salary': [25000, 30000, 28000, 35000]}

In [27]:
pd.DataFrame(d_list)

       0   1          2      3
0    Ram  20     Butwal  25000
1  Shyam  22  Kathmandu  30000
2   Hari  21    Pokhara  28000
3   Sita  23    Chitwan  35000

In [29]:
import numpy as np

peo = np.array([
    ["Ram", 20, "Butwal", 25000],
    ["Shyam", 22, "Kathmandu", 30000],
    ["Hari", 21, "Pokhara", 28000],
    ["Sita", 23, "Chitwan", 35000]
])

print(peo)

[['Ram' '20' 'Butwal' '25000']
 ['Shyam' '22' 'Kathmandu' '30000']
 ['Hari' '21' 'Pokhara' '28000']
 ['Sita' '23' 'Chitwan' '35000']]

In [30]:
pd.DataFrame(peo)

       0   1          2      3
0    Ram  20     Butwal  25000
1  Shyam  22  Kathmandu  30000
2   Hari  21    Pokhara  28000
3   Sita  23    Chitwan  35000

In [37]:
columns = ['Name','Age','City','Salary']
columns

['Name', 'Age', 'City', 'Salary']

In [41]:
col=pd.DataFrame(peo, columns=columns)
col

    Name Age       City Salary
0    Ram  20     Butwal  25000
1  Shyam  22  Kathmandu  30000
2   Hari  21    Pokhara  28000
3   Sita  23    Chitwan  35000

In [ ]:
# selection and indexing of columns

In [42]:
col

    Name Age       City Salary
0    Ram  20     Butwal  25000
1  Shyam  22  Kathmandu  30000
2   Hari  21    Pokhara  28000
3   Sita  23    Chitwan  35000

In [49]:
col['Name']

0      Ram
1    Shyam
2     Hari
3     Sita
Name: Name, dtype: object

In [51]:
col['City']

0       Butwal
1    Kathmandu
2      Pokhara
3      Chitwan
Name: City, dtype: object

In [52]:
col[['Age','Salary']]

  Age Salary
0  20  25000
1  22  30000
2  21  28000
3  23  35000

In [53]:
col["City"]

0       Butwal
1    Kathmandu
2      Pokhara
3      Chitwan
Name: City, dtype: object

In [54]:
col[['Name','Salary']]

    Name Salary
0    Ram  25000
1  Shyam  30000
2   Hari  28000
3   Sita  35000

In [55]:
col

    Name Age       City Salary
0    Ram  20     Butwal  25000
1  Shyam  22  Kathmandu  30000
2   Hari  21    Pokhara  28000
3   Sita  23    Chitwan  35000

In [57]:
#creating new column
col['Post'] = ["Doctor","Pilot","Sadhu","Brahmachari"]
col

    Name Age       City Salary         Post
0    Ram  20     Butwal  25000       Doctor
1  Shyam  22  Kathmandu  30000        Pilot
2   Hari  21    Pokhara  28000        Sadhu
3   Sita  23    Chitwan  35000  Brahmachari

In [ ]:
# removing column

In [61]:
col.drop('Salary', axis=1)

    Name Age       City         Post
0    Ram  20     Butwal       Doctor
1  Shyam  22  Kathmandu        Pilot
2   Hari  21    Pokhara        Sadhu
3   Sita  23    Chitwan  Brahmachari

In [77]:
col.drop('Salary', axis=1, inplace=True)

KeyError: "['Salary'] not found in axis"

In [74]:
col

    Name Age       City         Post
0    Ram  20     Butwal       Doctor
1  Shyam  22  Kathmandu        Pilot
2   Hari  21    Pokhara        Sadhu
3   Sita  23    Chitwan  Brahmachari

In [80]:
ar = np.array([
    [1, "Ram", 20, "Butwal", 25000],
    [2, "Shyam", 22, "Kathmandu", 30000],
    [3, "Hari", 21, "Pokhara", 28000],
    [4, "Sita", 23, "Chitwan", 35000]
])

column = ['S.N','Name','Age','City','Salary']

In [95]:
df =pd.DataFrame(ar,columns=column)
print(df)

  S.N   Name Age       City Salary
0   1    Ram  20     Butwal  25000
1   2  Shyam  22  Kathmandu  30000
2   3   Hari  21    Pokhara  28000
3   4   Sita  23    Chitwan  35000

In [96]:
df['paad'] = ['sanyas','sadhu','rishi','muni']
print(df)

  S.N   Name Age       City Salary    paad
0   1    Ram  20     Butwal  25000  sanyas
1   2  Shyam  22  Kathmandu  30000   sadhu
2   3   Hari  21    Pokhara  28000   rishi
3   4   Sita  23    Chitwan  35000    muni

In [167]:
df.drop(['paad','Age'], axis=1, inplace= True, errors='ignore')
print(df)

  S.N   Name       City Salary
0   1    Ram     Butwal  25000
1   2  Shyam  Kathmandu  30000
2   3   Hari    Pokhara  28000
3   4   Sita    Chitwan  35000

In [98]:
df

  S.N   Name Age       City Salary
0   1    Ram  20     Butwal  25000
1   2  Shyam  22  Kathmandu  30000
2   3   Hari  21    Pokhara  28000
3   4   Sita  23    Chitwan  35000

In [109]:
df.drop(columns=['paad','Age'], inplace=True, errors= 'ignore')
df

  S.N   Name       City Salary
0   1    Ram     Butwal  25000
1   2  Shyam  Kathmandu  30000
2   3   Hari    Pokhara  28000
3   4   Sita    Chitwan  35000

In [115]:
df.drop(1, axis=0)

  S.N  Name     City Salary
0   1   Ram   Butwal  25000
2   3  Hari  Pokhara  28000
3   4  Sita  Chitwan  35000

In [ ]:
# selectiong row

In [118]:
df

  S.N   Name       City Salary
0   1    Ram     Butwal  25000
1   2  Shyam  Kathmandu  30000
2   3   Hari    Pokhara  28000
3   4   Sita    Chitwan  35000

In [124]:
df.loc[[0,1]]

  S.N   Name       City Salary
0   1    Ram     Butwal  25000
1   2  Shyam  Kathmandu  30000

In [ ]:
# selection substes of rows and colomns

In [135]:
df.loc[[0,1]][['City','Salary']]

        City Salary
0     Butwal  25000
1  Kathmandu  30000

In [140]:
df

  S.N   Name       City Salary
0   1    Ram     Butwal  25000
1   2  Shyam  Kathmandu  30000
2   3   Hari    Pokhara  28000
3   4   Sita    Chitwan  35000

In [144]:
df.loc[[2,3]][['Name','City']]

   Name     City
2  Hari  Pokhara
3  Sita  Chitwan

In [ ]:
#Conditional selection
 # select age > 20

In [146]:
col

    Name Age       City
0    Ram  20     Butwal
1  Shyam  22  Kathmandu
2   Hari  21    Pokhara
3   Sita  23    Chitwan

In [153]:
col[col['Age'] > '20']

    Name Age       City
1  Shyam  22  Kathmandu
2   Hari  21    Pokhara
3   Sita  23    Chitwan

In [165]:
col[(col['Age'] > "20") & (col['City'] == 'Chitwan')]

   Name Age     City
3  Sita  23  Chitwan