In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Category': ['Food', 'Food', 'Electronics', 'Electronics', 'Clothing', 'Clothing'],
    'Store': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [500, 700, 1200, 1500, 400, 600],
    'Quantity': [5, 7, 2, 3, 4, 6],
    'Date': ['2026-01-01', '2026-01-01', '2026-01-02', '2026-01-02', '2026-01-03', '2026-01-03']
})
df

      Category Store  Sales  Quantity        Date
0         Food     A    500         5  2026-01-01
1         Food     B    700         7  2026-01-01
2  Electronics     A   1200         2  2026-01-02
3  Electronics     B   1500         3  2026-01-02
4     Clothing     A    400         4  2026-01-03
5     Clothing     B    600         6  2026-01-03

In [12]:
x=df.groupby('Category')['Sales'].sum()
x

Category
Clothing       1000
Electronics    2700
Food           1200
Name: Sales, dtype: int64

In [14]:
df.groupby("Store")['Sales'].sum()

Store
A    2100
B    2800
Name: Sales, dtype: int64

In [17]:
df.groupby(['Category','Store'])['Sales'].sum()

Category     Store
Clothing     A         400
             B         600
Electronics  A        1200
             B        1500
Food         A         500
             B         700
Name: Sales, dtype: int64

In [18]:
df

      Category Store  Sales  Quantity        Date
0         Food     A    500         5  2026-01-01
1         Food     B    700         7  2026-01-01
2  Electronics     A   1200         2  2026-01-02
3  Electronics     B   1500         3  2026-01-02
4     Clothing     A    400         4  2026-01-03
5     Clothing     B    600         6  2026-01-03

In [ ]:
#aggregation

In [24]:
df["Sales"].mean()

np.float64(816.6666666666666)

In [28]:
df['Sales'].agg(['mean','min','max'])

mean     816.666667
min      400.000000
max     1500.000000
Name: Sales, dtype: float64