In [8]:
import numpy as np
import pandas as pd

x = pd.DataFrame({
    "rank": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],

    "ep_title": [
        "The Beginning (12 ep) 2009-2011",
        "Shadow Fight (24 ep) 2010-2012",
        "Dragon Awakens (18 ep) 2011-2013",
        "Lost Kingdom (20 ep) 2012-2014",
        "Final Battle (15 ep) 2013-2015",
        "Blue Moon (13 ep) 2014-2016",
        "Dark Warrior (22 ep) 2010-2014",
        "Phoenix Rising (16 ep) 2009-2013",
        "Silent Ninja (11 ep) 2015-2016",
        "Crimson Storm (25 ep) 2011-2016",
        "Ancient Scroll (14 ep) 2012-2014",
        "Ocean Guardian (19 ep) 2013-2015",
        "Hidden Truth (17 ep) 2010-2012",
        "Eternal Promise (21 ep) 2014-2017",
        "Sky Legends (23 ep) 2009-2012",
        "Mystic Cave (10 ep) 2015-2017",
        "Golden Sword (26 ep) 2011-2015",
        "Last Samurai (12 ep) 2013-2016",
        "Frozen Flame (18 ep) 2012-2014",
        "Beyond Time (24 ep) 2010-2013"
    ],

    "score": [
        9.8,9.7,9.6,9.5,9.4,
        9.3,9.2,9.1,9.0,8.9,
        8.8,8.7,8.6,8.5,8.4,
        8.3,8.2,8.1,8.0,7.9
    ]
})

# Save CSV file
x.to_csv("anime.csv", index=False)

print(x)

    rank                           ep_title  score
0      1    The Beginning (12 ep) 2009-2011    9.8
1      2     Shadow Fight (24 ep) 2010-2012    9.7
2      3   Dragon Awakens (18 ep) 2011-2013    9.6
3      4     Lost Kingdom (20 ep) 2012-2014    9.5
4      5     Final Battle (15 ep) 2013-2015    9.4
5      6        Blue Moon (13 ep) 2014-2016    9.3
6      7     Dark Warrior (22 ep) 2010-2014    9.2
7      8   Phoenix Rising (16 ep) 2009-2013    9.1
8      9     Silent Ninja (11 ep) 2015-2016    9.0
9     10    Crimson Storm (25 ep) 2011-2016    8.9
10    11   Ancient Scroll (14 ep) 2012-2014    8.8
11    12   Ocean Guardian (19 ep) 2013-2015    8.7
12    13     Hidden Truth (17 ep) 2010-2012    8.6
13    14  Eternal Promise (21 ep) 2014-2017    8.5
14    15      Sky Legends (23 ep) 2009-2012    8.4
15    16      Mystic Cave (10 ep) 2015-2017    8.3
16    17     Golden Sword (26 ep) 2011-2015    8.2
17    18     Last Samurai (12 ep) 2013-2016    8.1
18    19     Frozen Flame (18 ep) 2012-2014    8.0
19    20      Beyond Time (24 ep) 2010-2013    7.9

In [9]:
x.head()

   rank                          ep_title  score
0     1   The Beginning (12 ep) 2009-2011    9.8
1     2    Shadow Fight (24 ep) 2010-2012    9.7
2     3  Dragon Awakens (18 ep) 2011-2013    9.6
3     4    Lost Kingdom (20 ep) 2012-2014    9.5
4     5    Final Battle (15 ep) 2013-2015    9.4

In [66]:
anime.loc[2]['ep_title']

'Dragon Awakens (18 ep) 2011-2013'

In [11]:
#         Mske a new column for count Episodes

def extract_episode(txt):
    check = False
    data = ''
    for i in txt:
        if i == ')':
            check = False
            
        if i == '(':
            check = True
            continue
        if check == True:
            data += i
            
    return data

In [12]:
x['Episodes']=x['ep_title'].apply(extract_episode)
x

    rank                           ep_title  score Episodes
0      1    The Beginning (12 ep) 2009-2011    9.8    12 ep
1      2     Shadow Fight (24 ep) 2010-2012    9.7    24 ep
2      3   Dragon Awakens (18 ep) 2011-2013    9.6    18 ep
3      4     Lost Kingdom (20 ep) 2012-2014    9.5    20 ep
4      5     Final Battle (15 ep) 2013-2015    9.4    15 ep
5      6        Blue Moon (13 ep) 2014-2016    9.3    13 ep
6      7     Dark Warrior (22 ep) 2010-2014    9.2    22 ep
7      8   Phoenix Rising (16 ep) 2009-2013    9.1    16 ep
8      9     Silent Ninja (11 ep) 2015-2016    9.0    11 ep
9     10    Crimson Storm (25 ep) 2011-2016    8.9    25 ep
10    11   Ancient Scroll (14 ep) 2012-2014    8.8    14 ep
11    12   Ocean Guardian (19 ep) 2013-2015    8.7    19 ep
12    13     Hidden Truth (17 ep) 2010-2012    8.6    17 ep
13    14  Eternal Promise (21 ep) 2014-2017    8.5    21 ep
14    15      Sky Legends (23 ep) 2009-2012    8.4    23 ep
15    16      Mystic Cave (10 ep) 2015-2017    8.3    10 ep
16    17     Golden Sword (26 ep) 2011-2015    8.2    26 ep
17    18     Last Samurai (12 ep) 2013-2016    8.1    12 ep
18    19     Frozen Flame (18 ep) 2012-2014    8.0    18 ep
19    20      Beyond Time (24 ep) 2010-2013    7.9    24 ep

In [13]:
x['Episodes'] = x['Episodes'].str.replace(' ep',"")
x

    rank                           ep_title  score Episodes
0      1    The Beginning (12 ep) 2009-2011    9.8       12
1      2     Shadow Fight (24 ep) 2010-2012    9.7       24
2      3   Dragon Awakens (18 ep) 2011-2013    9.6       18
3      4     Lost Kingdom (20 ep) 2012-2014    9.5       20
4      5     Final Battle (15 ep) 2013-2015    9.4       15
5      6        Blue Moon (13 ep) 2014-2016    9.3       13
6      7     Dark Warrior (22 ep) 2010-2014    9.2       22
7      8   Phoenix Rising (16 ep) 2009-2013    9.1       16
8      9     Silent Ninja (11 ep) 2015-2016    9.0       11
9     10    Crimson Storm (25 ep) 2011-2016    8.9       25
10    11   Ancient Scroll (14 ep) 2012-2014    8.8       14
11    12   Ocean Guardian (19 ep) 2013-2015    8.7       19
12    13     Hidden Truth (17 ep) 2010-2012    8.6       17
13    14  Eternal Promise (21 ep) 2014-2017    8.5       21
14    15      Sky Legends (23 ep) 2009-2012    8.4       23
15    16      Mystic Cave (10 ep) 2015-2017    8.3       10
16    17     Golden Sword (26 ep) 2011-2015    8.2       26
17    18     Last Samurai (12 ep) 2013-2016    8.1       12
18    19     Frozen Flame (18 ep) 2012-2014    8.0       18
19    20      Beyond Time (24 ep) 2010-2013    7.9       24

In [16]:
x['Episodes'] = x['Episodes'].astype(int)

In [17]:
x['Episodes'].astype(int)

0     12
1     24
2     18
3     20
4     15
5     13
6     22
7     16
8     11
9     25
10    14
11    19
12    17
13    21
14    23
15    10
16    26
17    12
18    18
19    24
Name: Episodes, dtype: int64

In [18]:
# Make a new column for time stamp
x.loc[0]['ep_title']

'The Beginning (12 ep) 2009-2011'

In [37]:
def extract_time(txt):
    check = False
    data = ''
    for i in range(len(txt)):
        if txt[i] == ')':
            for j in range(i,i+9):
                data += txt[j]
            return data

In [38]:
x['ep_title'].apply(extract_time)

0     ) 2009-20
1     ) 2010-20
2     ) 2011-20
3     ) 2012-20
4     ) 2013-20
5     ) 2014-20
6     ) 2010-20
7     ) 2009-20
8     ) 2015-20
9     ) 2011-20
10    ) 2012-20
11    ) 2013-20
12    ) 2010-20
13    ) 2014-20
14    ) 2009-20
15    ) 2015-20
16    ) 2011-20
17    ) 2013-20
18    ) 2012-20
19    ) 2010-20
Name: ep_title, dtype: object

In [29]:
x['time'] = x['ep_title'].apply(extract_time)
x

    rank                           ep_title  score  Episodes       time
0      1    The Beginning (12 ep) 2009-2011    9.8        12  ) 2009-20
1      2     Shadow Fight (24 ep) 2010-2012    9.7        24  ) 2010-20
2      3   Dragon Awakens (18 ep) 2011-2013    9.6        18  ) 2011-20
3      4     Lost Kingdom (20 ep) 2012-2014    9.5        20  ) 2012-20
4      5     Final Battle (15 ep) 2013-2015    9.4        15  ) 2013-20
5      6        Blue Moon (13 ep) 2014-2016    9.3        13  ) 2014-20
6      7     Dark Warrior (22 ep) 2010-2014    9.2        22  ) 2010-20
7      8   Phoenix Rising (16 ep) 2009-2013    9.1        16  ) 2009-20
8      9     Silent Ninja (11 ep) 2015-2016    9.0        11  ) 2015-20
9     10    Crimson Storm (25 ep) 2011-2016    8.9        25  ) 2011-20
10    11   Ancient Scroll (14 ep) 2012-2014    8.8        14  ) 2012-20
11    12   Ocean Guardian (19 ep) 2013-2015    8.7        19  ) 2013-20
12    13     Hidden Truth (17 ep) 2010-2012    8.6        17  ) 2010-20
13    14  Eternal Promise (21 ep) 2014-2017    8.5        21  ) 2014-20
14    15      Sky Legends (23 ep) 2009-2012    8.4        23  ) 2009-20
15    16      Mystic Cave (10 ep) 2015-2017    8.3        10  ) 2015-20
16    17     Golden Sword (26 ep) 2011-2015    8.2        26  ) 2011-20
17    18     Last Samurai (12 ep) 2013-2016    8.1        12  ) 2013-20
18    19     Frozen Flame (18 ep) 2012-2014    8.0        18  ) 2012-20
19    20      Beyond Time (24 ep) 2010-2013    7.9        24  ) 2010-20

In [86]:
x['time'].max()

'26 ep'

    rank                           ep_title  score  Episodes   time
0      1    The Beginning (12 ep) 2009-2011    9.8        12  12 ep
1      2     Shadow Fight (24 ep) 2010-2012    9.7        24  24 ep
2      3   Dragon Awakens (18 ep) 2011-2013    9.6        18  18 ep
3      4     Lost Kingdom (20 ep) 2012-2014    9.5        20  20 ep
4      5     Final Battle (15 ep) 2013-2015    9.4        15  15 ep
5      6        Blue Moon (13 ep) 2014-2016    9.3        13  13 ep
6      7     Dark Warrior (22 ep) 2010-2014    9.2        22  22 ep
7      8   Phoenix Rising (16 ep) 2009-2013    9.1        16  16 ep
8      9     Silent Ninja (11 ep) 2015-2016    9.0        11  11 ep
9     10    Crimson Storm (25 ep) 2011-2016    8.9        25  25 ep
10    11   Ancient Scroll (14 ep) 2012-2014    8.8        14  14 ep
11    12   Ocean Guardian (19 ep) 2013-2015    8.7        19  19 ep
12    13     Hidden Truth (17 ep) 2010-2012    8.6        17  17 ep
13    14  Eternal Promise (21 ep) 2014-2017    8.5        21  21 ep
14    15      Sky Legends (23 ep) 2009-2012    8.4        23  23 ep
15    16      Mystic Cave (10 ep) 2015-2017    8.3        10  10 ep
16    17     Golden Sword (26 ep) 2011-2015    8.2        26  26 ep
17    18     Last Samurai (12 ep) 2013-2016    8.1        12  12 ep
18    19     Frozen Flame (18 ep) 2012-2014    8.0        18  18 ep
19    20      Beyond Time (24 ep) 2010-2013    7.9        24  24 ep

In [74]:
x['score'] = x['score'].astype(str).str.strip().astype(float)
print(x['score'].min())

9.8

In [ ]:
for i in x:
    if x['score']

In [77]:
x['ep_title'].head()

0     The Beginning (12 ep) 2009-2011
1      Shadow Fight (24 ep) 2010-2012
2    Dragon Awakens (18 ep) 2011-2013
3      Lost Kingdom (20 ep) 2012-2014
4      Final Battle (15 ep) 2013-2015
Name: ep_title, dtype: object

In [84]:
x[x['Episodes']  ==x['Episodes'].max()]

    rank                           ep_title  score  Episodes   time
0      1    The Beginning (12 ep) 2009-2011    9.8        26  12 ep
1      2     Shadow Fight (24 ep) 2010-2012    9.8        26  24 ep
2      3   Dragon Awakens (18 ep) 2011-2013    9.8        26  18 ep
3      4     Lost Kingdom (20 ep) 2012-2014    9.8        26  20 ep
4      5     Final Battle (15 ep) 2013-2015    9.8        26  15 ep
5      6        Blue Moon (13 ep) 2014-2016    9.8        26  13 ep
6      7     Dark Warrior (22 ep) 2010-2014    9.8        26  22 ep
7      8   Phoenix Rising (16 ep) 2009-2013    9.8        26  16 ep
8      9     Silent Ninja (11 ep) 2015-2016    9.8        26  11 ep
9     10    Crimson Storm (25 ep) 2011-2016    9.8        26  25 ep
10    11   Ancient Scroll (14 ep) 2012-2014    9.8        26  14 ep
11    12   Ocean Guardian (19 ep) 2013-2015    9.8        26  19 ep
12    13     Hidden Truth (17 ep) 2010-2012    9.8        26  17 ep
13    14  Eternal Promise (21 ep) 2014-2017    9.8        26  21 ep
14    15      Sky Legends (23 ep) 2009-2012    9.8        26  23 ep
15    16      Mystic Cave (10 ep) 2015-2017    9.8        26  10 ep
16    17     Golden Sword (26 ep) 2011-2015    9.8        26  26 ep
17    18     Last Samurai (12 ep) 2013-2016    9.8        26  12 ep
18    19     Frozen Flame (18 ep) 2012-2014    9.8        26  18 ep
19    20      Beyond Time (24 ep) 2010-2013    9.8        26  24 ep

In [85]:
x['time'].max()

'26 ep'

In [87]:
x['ep_title'].count()

np.int64(20)