In [1]:
import numpy as np
import pandas as pd

In [ ]:
#merge 2 data fdataframe_columns

In [5]:
stu = pd.DataFrame({
    'Student_ID': [1, 2, 3, 4],
    'Name': ['Ram', 'Sita', 'Hari', 'Gita'],
    'Class': [12, 12, 11, 10]
}) 
stu

   Student_ID  Name  Class
0           1   Ram     12
1           2  Sita     12
2           3  Hari     11
3           4  Gita     10

In [6]:
mks = pd.DataFrame({
    'Student_ID': [1, 2, 5, 6],
    'Subject': ['Math', 'Science', 'Computer', 'English'],
    'Marks': [85, 90, 78, 88]
})
mks

   Student_ID   Subject  Marks
0           1      Math     85
1           2   Science     90
2           5  Computer     78
3           6   English     88

In [7]:
pd.merge(stu,mks)

   Student_ID  Name  Class  Subject  Marks
0           1   Ram     12     Math     85
1           2  Sita     12  Science     90

In [10]:
pd.merge(stu,mks,how="outer")

   Student_ID  Name  Class   Subject  Marks
0           1   Ram   12.0      Math   85.0
1           2  Sita   12.0   Science   90.0
2           3  Hari   11.0       NaN    NaN
3           4  Gita   10.0       NaN    NaN
4           5   NaN    NaN  Computer   78.0
5           6   NaN    NaN   English   88.0

In [15]:
pd.merge(stu,mks,on="Student_ID",how='inner')

   Student_ID  Name  Class  Subject  Marks
0           1   Ram     12     Math     85
1           2  Sita     12  Science     90

In [13]:
pd.merge(stu,mks,on="Student_ID",how='outer')

   Student_ID  Name  Class   Subject  Marks
0           1   Ram   12.0      Math   85.0
1           2  Sita   12.0   Science   90.0
2           3  Hari   11.0       NaN    NaN
3           4  Gita   10.0       NaN    NaN
4           5   NaN    NaN  Computer   78.0
5           6   NaN    NaN   English   88.0

In [16]:
pd.merge(stu,mks,on="Student_ID",how='left')

   Student_ID  Name  Class  Subject  Marks
0           1   Ram     12     Math   85.0
1           2  Sita     12  Science   90.0
2           3  Hari     11      NaN    NaN
3           4  Gita     10      NaN    NaN

In [17]:
pd.merge(stu,mks,on="Student_ID",how='right')

   Student_ID  Name  Class   Subject  Marks
0           1   Ram   12.0      Math     85
1           2  Sita   12.0   Science     90
2           5   NaN    NaN  Computer     78
3           6   NaN    NaN   English     88

In [18]:
stu

   Student_ID  Name  Class
0           1   Ram     12
1           2  Sita     12
2           3  Hari     11
3           4  Gita     10

In [19]:
mks

   Student_ID   Subject  Marks
0           1      Math     85
1           2   Science     90
2           5  Computer     78
3           6   English     88

In [21]:
#Concating
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': ['Ram', 'Sita', 'Hari', 'Gita'],
    'C': [85, 90, 78, 88]
}) 
df1

   A     B   C
0  1   Ram  85
1  2  Sita  90
2  3  Hari  78
3  4  Gita  88

In [22]:
df2 = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': ['Math', 'Science', 'Computer', 'English'],
    'C': ['Pass', 'Pass', 'Pass', 'Pass']
})
df2

   A         B     C
0  1      Math  Pass
1  2   Science  Pass
2  3  Computer  Pass
3  4   English  Pass

In [24]:
pd.concat([df1,df2])

   A         B     C
0  1       Ram    85
1  2      Sita    90
2  3      Hari    78
3  4      Gita    88
0  1      Math  Pass
1  2   Science  Pass
2  3  Computer  Pass
3  4   English  Pass

In [25]:
pd.concat([df2,df1])

   A         B     C
0  1      Math  Pass
1  2   Science  Pass
2  3  Computer  Pass
3  4   English  Pass
0  1       Ram    85
1  2      Sita    90
2  3      Hari    78
3  4      Gita    88

In [26]:
pd.concat([df1,df2],axis=1)

   A     B   C  A         B     C
0  1   Ram  85  1      Math  Pass
1  2  Sita  90  2   Science  Pass
2  3  Hari  78  3  Computer  Pass
3  4  Gita  88  4   English  Pass

In [ ]:
#joining

In [27]:
df3 = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': ['Ram', 'Sita', 'Hari', 'Gita'],
    'C': [85, 90, 78, 88]
})
df3

   A     B   C
0  1   Ram  85
1  2  Sita  90
2  3  Hari  78
3  4  Gita  88

In [28]:
df4 = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'D': ['Math', 'Science', 'Computer', 'English'],
    'E': ['Pass', 'Pass', 'Pass', 'Pass']
})
df4

   A         D     E
0  1      Math  Pass
1  2   Science  Pass
2  3  Computer  Pass
3  4   English  Pass

In [42]:
x = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': ['Ram', 'Sita', 'Hari', 'Gita'],
    'C': [85, 90, 78, 88]
})
y = pd.DataFrame({
    'A': [2, 3, 4,5],
    'D': ['Math', 'Science', 'Computer', 'English'],
    'E': ['Pass', 'Pass', 'Pass', 'Pass']
})

   A         D     E
0  2      Math  Pass
1  3   Science  Pass
2  4  Computer  Pass
3  5   English  Pass

In [43]:
x

   A     B   C
0  1   Ram  85
1  2  Sita  90
2  3  Hari  78
3  4  Gita  88

In [45]:
x.join(y,how='outer')

ValueError: columns overlap but no suffix specified: Index(['A'], dtype='object')