In [1]:
import numpy as np
import pandas as pd

In [6]:
#Missing Data

In [26]:
data = {
    'A': [10, 20, 1, 40, 50],
    'B': [np.nan, 15, 25, 35, 45],
    'C': [5, np.nan, 15, 20, np.nan],
    'D': [100, 200, 300, np.nan, np.nan],
    'E': [1, 2, 3, 4, 5]
}
df = pd.DataFrame(data)
df

    A     B     C      D  E
0  10   NaN   5.0  100.0  1
1  20  15.0   NaN  200.0  2
2   1  25.0  15.0  300.0  3
3  40  35.0  20.0    NaN  4
4  50  45.0   NaN    NaN  5

In [13]:
df.isna()

       A      B      C      D      E
0  False   True  False  False  False
1  False  False   True  False  False
2   True  False  False  False  False
3  False  False  False   True  False
4  False  False   True   True  False

In [14]:
df.isna().sum()

A    1
B    1
C    2
D    2
E    0
dtype: int64

In [15]:
#missing value in each column 
df.isna().any()

A     True
B     True
C     True
D     True
E    False
dtype: bool

In [18]:
df.isna().any().sum()

np.int64(4)

In [21]:
#removing null
df.dropna()

   A     B     C      D  E
2  1  25.0  15.0  300.0  3

In [22]:
df

    A     B     C      D  E
0  10   NaN   5.0  100.0  1
1  20  15.0   NaN  200.0  2
2   1  25.0  15.0  300.0  3
3  40  35.0  20.0    NaN  4
4  50  45.0   NaN    NaN  5

In [30]:
df.dropna(thresh=3)

    A     B     C      D  E
0  10   NaN   5.0  100.0  1
1  20  15.0   NaN  200.0  2
2   1  25.0  15.0  300.0  3
3  40  35.0  20.0    NaN  4
4  50  45.0   NaN    NaN  5

In [31]:
#filling the missing ddata
df

    A     B     C      D  E
0  10   NaN   5.0  100.0  1
1  20  15.0   NaN  200.0  2
2   1  25.0  15.0  300.0  3
3  40  35.0  20.0    NaN  4
4  50  45.0   NaN    NaN  5

In [32]:
df.fillna(0)

    A     B     C      D  E
0  10   0.0   5.0  100.0  1
1  20  15.0   0.0  200.0  2
2   1  25.0  15.0  300.0  3
3  40  35.0  20.0    0.0  4
4  50  45.0   0.0    0.0  5

In [33]:
df

    A     B     C      D  E
0  10   NaN   5.0  100.0  1
1  20  15.0   NaN  200.0  2
2   1  25.0  15.0  300.0  3
3  40  35.0  20.0    NaN  4
4  50  45.0   NaN    NaN  5

In [36]:
df.fillna(0,inplace=True)
df

    A     B     C      D  E
0  10   0.0   5.0  100.0  1
1  20  15.0   0.0  200.0  2
2   1  25.0  15.0  300.0  3
3  40  35.0  20.0    0.0  4
4  50  45.0   0.0    0.0  5

In [40]:
values = {'A':10,'B':100,'C':200,'D':300,'E':400}
df.fillna(value=values,inplace=True)
df

    A     B     C      D  E
0  10   0.0   5.0  100.0  1
1  20  15.0   0.0  200.0  2
2   1  25.0  15.0  300.0  3
3  40  35.0  20.0    0.0  4
4  50  45.0   0.0    0.0  5

In [42]:
#fill the mean in placr of nan
df.fillna(df.mean())
df.mean()

A     24.2
B     24.0
C      8.0
D    120.0
E      3.0
dtype: float64