In [1]:
import numpy as np
import pandas as pd

In [16]:
pd.pivot_table(df,values='Sales', index='Region',columns='Product',aggfunc='median')

Product  Laptop   Phone  Tablet
Region
East     5000.0  3000.0  2000.0
West     7000.0  4500.0  3500.0

In [17]:
p2 = pd.pivot_table(df,values=['Sales','Units'], index='Region',columns='Product')
p2

          Sales                  Units
Product  Laptop   Phone  Tablet Laptop Phone Tablet
Region
East     5000.0  3000.0  2000.0    5.0   3.0    2.0
West     7000.0  4500.0  3500.0    7.0   4.0    3.0

In [ ]:
#operationsall

In [18]:
df = pd.DataFrame({
    'A': [10, 20, 30, 40, 50],
    'B': [5, 15, 25, 35, 45],
    'C': [2, 4, 6, 8, 10]
})
df

    A   B   C
0  10   5   2
1  20  15   4
2  30  25   6
3  40  35   8
4  50  45  10

In [19]:
df.shape

(5, 3)

In [20]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [26]:
df.rpow

<bound method DataFrame.rpow of     A   B   C
0  10   5   2
1  20  15   4
2  30  25   6
3  40  35   8
4  50  45  10>

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [28]:
df.describe()

               A          B          C
count   5.000000   5.000000   5.000000
mean   30.000000  25.000000   6.000000
std    15.811388  15.811388   3.162278
min    10.000000   5.000000   2.000000
25%    20.000000  15.000000   4.000000
50%    30.000000  25.000000   6.000000
75%    40.000000  35.000000   8.000000
max    50.000000  45.000000  10.000000

In [29]:
df['A']+10

0    20
1    30
2    40
3    50
4    60
Name: A, dtype: int64

In [ ]:
# data frame applyinf functions

In [30]:
df

    A   B   C
0  10   5   2
1  20  15   4
2  30  25   6
3  40  35   8
4  50  45  10

0                   23283064365386962890625
1    43143988327398919500410556793212890625
2    10714783335207889188713531907079020289
3    43771668181157649408097001744154798721
4    21459328726220295749330255864341015681
Name: B, dtype: object

In [60]:
dfx = pd.DataFrame({
    'A': [10, 20, 30, 40, 50],
    'B': [5, 15, 25, 35, 45],
    'C': [2, 4, 6, 8, 10]
})
dfx

    A   B   C
0  10   5   2
1  20  15   4
2  30  25   6
3  40  35   8
4  50  45  10

In [72]:
def square(x):
    return x**2

In [74]:
dfx[B].apply(square)

NameError: name 'B' is not defined

In [79]:
import pandas as pd

dfx = pd.DataFrame({
    'A': [10, 20, 30, 40, 50],
    'B': [5, 15, 25, 35, 45],
    'C': [2, 4, 6, 8, 10]
})

def square(x):
    return x ** 2

dfx["d"] = dfx["B"].apply(square)

print(result)

0      25
1     225
2     625
3    1225
4    2025
Name: B, dtype: int64

In [80]:
dfx

    A   B   C     d
0  10   5   2    25
1  20  15   4   225
2  30  25   6   625
3  40  35   8  1225
4  50  45  10  2025